import AppKit

@MainActor
enum SensitivePasteboard {
    static let marker = NSPasteboard.PasteboardType("local.paul.sensitive")
    static let excludedTypes = [marker,
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")]

    static func shouldExclude(_ pasteboard: NSPasteboard) -> Bool {
        excludedTypes.contains { pasteboard.types?.contains($0) == true }
    }

    static func write(_ text: String, to pasteboard: NSPasteboard = .general, expires: Bool) {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("", forType: marker)
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        let count = pasteboard.changeCount
        if expires {
            Task { @MainActor in
                try? await Task.sleep(for: .seconds(60))
                clearIfUnchanged(pasteboard, expectedChangeCount: count)
            }
        }
    }

    static func clearIfUnchanged(_ pasteboard: NSPasteboard, expectedChangeCount: Int) {
        guard pasteboard.changeCount == expectedChangeCount,
              pasteboard.types?.contains(marker) == true else { return }
        pasteboard.clearContents()
    }
}
